name: Basic Checkout Lab

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

env:
    CUSTOM_MESSAGE: "Hello from GitHub Actions!"

jobs:

  basic-checkout:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: List repository contents
      - name: List files
        run: ls -la

      # Step 3: Display system information
      - name: Show system info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Operating System: $(uname -a)"
          echo "Current Directory: $(pwd)"

      # Step 4: Check software versions
      - name: Check versions
        run: |
          echo "Node version: $(node --version)"
          echo "Python version: $(python --version)"
          echo "Git version: $(git --version)"

      # Step 5: Check datetime, free disk space and memory usage
      - name: Current date and time
        run: |
          echo "Current Date and Time: $(date)"
          echo "Available Disk Space: $(df -h)"
          echo "Memory Usage: $(free -m)"

      # Print custom environment varriable
      - name: Display custom message
        run: echo "$CUSTOM_MESSAGE"

      # Coditionl Execution
      - name: Conditional step
        if: github.event_name == 'push'
        run: echo "This waas triggered by a push event"
